[build-system]
requires = ["setuptools>=65.0.0", "wheel>=0.38.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dashboard-logistico"
version = "1.0.0"
description = "Dashboard Logístico com Flask"
requires-python = ">=3.11"
